### ISSUE TITLE
A question about RavenDB listeners

### ISSUE THREAD

**Issue by simonfox** [mauroservienti/Conferences#1]
Hi Mauro

Hope you don't mind me asking a couple of questions via an issue here?

I came across your Full Stack Sample via some of the videos you have on the HibernatingRhinos YouTube channel and was wondering a couple of things...

I see you are using a repository to abstract the creation of commits and the ES events that are generated by operations on your aggregate roots. It seems like a pretty legitimate use of a repository as it is only used to load a document by id in order to apply a command (and thus the discussion about not abstracting the raven session isn't really relevant here). What would your thoughts/opinion be on doing this sort of thing via a RavenDB listener instead of the repository? That way the document store could be configured up front to use the listener, and your handlers could just use the session directly?

Thanks in advance
Simon

**Comment by mauroservienti** [comment]
@simonfox 

> Hope you don't mind me asking a couple of questions via an issue here?

absolutely, it is the right place. And sorry the long delay.

> I came across your Full Stack Sample via some of the videos you have on the HibernatingRhinos YouTube channel and was wondering a couple of things...
> I see you are using a repository to abstract the creation of commits and the ES events that are generated by operations on your aggregate roots. It seems like a pretty legitimate use of a repository as it is only used to load a document by id in order to apply a command (and thus the discussion about not abstracting the raven session isn't really relevant here). What would your thoughts/opinion be on doing this sort of thing via a RavenDB listener instead of the repository? That way the document store could be configured up front to use the listener, and your handlers could just use the session directly?

Can be a viable approach, each time the listener "sees", on store, an aggregate that has uncommitted events can retrieve those events, store them in the same transaction as the aggregate and if required push them on a queue.

The only thing that comes to my mind that is not immediate is, in the listener, how to access to _current_ document session instance given that it is controlled by the user the only option I see is to require the user to register it in some "current context" in order to allow the listener to access it.

Or am I missing something?

**Comment by simonfox** [comment]
@mauroservienti 

aha, I'm sorry I'm new to Raven and I had guessed that the listener implementation would be similar to NHibernate where I can get hold of the session. But you are correct, it is not easily accessible from the listener and some "context" would need to be set up. The pushing to a queue could still be done easily enough from the listener I suppose.

Thanks for your reply!

**Comment by mauroservienti** [comment]
> The pushing to a queue could still be done easily enough from the listener I suppose.

yes, basically you can depend on the bus implementation in the listener given that the bus itself is a singleton.
